#!/bin/sh
if [[ "$1" =~ ^~ ]]
then
	echo "\~ -> $HOME"
        f="$HOME$(echo \"$1\" | cut -c 2-)"
elif [[ "$1" =~ ^/ ]]
then
	f="$1"
else
	f="$(pwd)/$1"
fi
REQ_HEX="0"
echo "true" > /tmp/nonsgn.dat
codesign -d -r- "$f" 2>&1 | awk -F ' => ' '/designated/{print $2}' | csreq -r- -b /tmp/csreq.bin 2> /dev/null ||(
	codesign --detached /tmp/app.sig -s - "$f"
        REQ_STR=$(codesign -d -r- --detached /tmp/app.sig "$f" 2> /dev/null | grep '# designated =>' | sed 's/# designated => //g')
        echo "$REQ_STR" | csreq -r- -b /tmp/csreq.bin
        echo "false" > /tmp/nonsgn.dat
)
REQ_HEX=$(xxd -p /tmp/csreq.bin  | tr -d '\n')
__NUM=1
$(cat /tmp/nonsgn.dat) &&\
        __NUM=0 &&\
        f=$(osascript -e "id of app \"$f\"")
echo "$f"
echo "$REQ_HEX"
__DATE=$(date +%s)
sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "
        DELETE FROM \"access\" where client = '$f' and service = 'kTCCServiceAccessibility';
        DELETE FROM \"access\" where csreq = X'$REQ_HEX' and service = 'kTCCServiceAccessibility';
        INSERT INTO \"access\" VALUES('kTCCServiceAccessibility','$f',$__NUM,2,4,1,X'$REQ_HEX',NULL,0,0,NULL,0,$__DATE,NULL,NULL,'',$__DATE)
"

